name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black flake8 mypy
          pip install -e .

      - name: Run Black
        run: black --line-length 79 --check .

      - name: Run Flake8
        run: flake8 retry_lib tests

      - name: Run Mypy
        run: mypy retry_lib

      - name: Run Pytest
        run: pytest -v
